# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24d79886ead79c035568cfdb6e80efb365bff4c1460f72e5e0bbd2fcdd55ca43b5801940af8e7e949bc56474707c6994cc41a2d75db30fbcee03bd2d0c9c025c

test:
  secret_key_base: 8c1ab6297d29dece1f87d559dd4b90fe72b95aae7ab440b5457c70057e8d54ce69ae7976ace79bd246c8831b0e8a9f8849ae7266e1b4c9a354d5bfb4fddfd37b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
